DELIMITER //
CREATE PROCEDURE SP_ROLES_BY_USER
(
	IN USER_NAME CHAR(10)
)
BEGIN
	SELECT R.ROLE_ID, R.ROLE_NAME, R.DESCRIPTION, R.ACTIVED
	FROM ROLE R INNER JOIN USER_ROLE UR ON R.ROLE_ID = UR.ROLE_ID INNER JOIN USER U ON U.USER_ID = UR.USER_ID 
	WHERE R.ACTIVED = 1 AND U.ACTIVED = 1 AND U.USERNAME = USER_NAME;
END //
DELIMITER ;