DELIMITER //
CREATE PROCEDURE SP_ROLES_BY_USER
(
	IN USER_NAME CHAR(10)
)
BEGIN
	SELECT R.ROLE_ID, R.ROLE_NAME, R.DESCRIPTION, R.ACTIVED
	FROM ROLE R INNER JOIN USER_ROLE UR ON R.ROLE_ID = UR.ROLE_ID INNER JOIN USER U ON U.USER_ID = UR.USER_ID 
	WHERE R.ACTIVED = 1 AND U.ACTIVED = 1 AND U.USERNAME = USER_NAME;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE SP_ADD_ROLE_BY_USER
(
	IN USER_NAME_X CHAR(10),
    IN ROLE_NAME_X CHAR(10)
)
BEGIN
	DECLARE USERID INT DEFAULT 0;
    DECLARE ROLEID INT DEFAULT 0;
    SELECT USER_ID INTO USERID FROM USER WHERE ACTIVED= 1 AND USERNAME = USER_NAME_X;
    SELECT ROLE_ID INTO ROLEID FROM ROLE WHERE ACTIVED= 1 AND ROLE_NAME = ROLE_NAME_X;
    
    IF USERID > 0 THEN
		INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (USERID, ROLEID);
		COMMIT;
	END IF;
END //
DELIMITER ;